### ISSUE TITLE
savestate.open expects Path object but documentation shows to use a string

### ISSUE THREAD

**Issue by hermlon** [MrThearMan/savestate#3]
### I have read the docs thoroughly before making this bug report.

- [X] Yes

### I have read through other open issues, and my issue is not a duplicate.

- [X] Yes

### What version of the library you are using?

0.0.1

### Which python version are you using?

3.9

### What operating system are you on?

Ubuntu

### Description

When running the following code:
```
import savestate                                                                                                                                                                      
savestate.open('test', 'c')                                                                                                                                                           
```
I get the following error:
```
Traceback (most recent call last):                                                                                                                                                        
  File "<stdin>", line 1, in <module>                                                                                                                                                     
  File "/home/neville/.local/lib/python3.9/site-packages/savestate/savestate.py", line 762, in open                                                                                       
    filename = _add_file_identifier(filename)                                                                                                                                             
  File "/home/neville/.local/lib/python3.9/site-packages/savestate/savestate.py", line 734, in _add_file_identifier
    if filename.suffix == FILE_SUFFIX:
AttributeError: 'str' object has no attribute 'suffix'
```

Passing a `Path('test')` object instead works (as the open method expects a Path object). I think this should be changed in the documentation at https://mrthearman.github.io/savestate/quick/ or the method should accept a string again.

**Comment by MrThearMan** [comment]
Thank you for the report! I added back support for strings for `savestate.open` in [0.1.1](https://github.com/MrThearMan/savestate/releases/tag/v0.1.1).
